server:
  port: 9092
  profiles:
    active: local

spring:
  application:
    name: blogspring
  datasource:
    name: blog_core
    url: jdbc:mysql://118.25.25.13:3096/singleboot?charset=utf8&useSSL=false&serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: J

logback:
  appName: blog-spring
  fileType: log
  logDir: logs